name: Create Zip Archive with Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: vimtor/action-zip@v1.2
      with:
        files: assets/ pack.mcmeta pack.png
        dest: Sticky Pistons Plus.zip
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ${{ github.workspace }}/Sticky Pistons Plus.zip
