name: Create Zip Archive with Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        files: assets/ pack.mcmeta pack.png
        name: Sticky Pistons Plus
        path: ${{ github.workspace }}
