name: Create Zip Archive with Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sticky Pistons Plus
          path: |
            ${{ github.workspace }}/pack.mcmeta
            pack.png
            assets/
